type AuthPayload {
  accessToken: String!
  refreshToken: String!
  usuario: Usuario!
}

type Categoria {
  id: Int!
  nombre: String!
  productos: [Producto!]!
}

type DetallePedido {
  id: Int!
  cantidad: Int!
  importe: Float!
  producto: Producto!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  crearProducto(datos: ProductoInput!): Producto!
  actualizarProducto(id: Int!, datos: ProductoInput!): Producto
  eliminarProducto(id: Int!): Boolean!
  crearPedido(datos: PedidoInput!): Pedido!
  crearUsuario(datos: UsuarioInput!): Usuario
  login(datos: LoginInput!): AuthPayload!
  refrescarToken(refreshToken: String!): RefreshPayload!
  logout(refreshToken: String!): Boolean!
}

type Pedido {
  id: Int!
  fecha: String!
  total: Float!
  status: String!
  usuario: Usuario!
  detalles: [DetallePedido!]!
}

input PedidoInput {
  renglones: [RenglonInput!]!
}

type Producto {
  id: Int!
  nombre: String!
  precio: Float!
  imagen: String
  disponible: Boolean
  categoria: Categoria!
}

input ProductoInput {
  nombre: String!
  precio: Float!
  imagen: String = null
  categoria: Int!
  disponible: Boolean = null
}

type Query {
  productos(limite: Int = null, desde: Int = null): [Producto!]!
  producto(id: Int!): Producto
  categorias: [Categoria!]!
  categoria(id: Int!): Categoria
  pedidos(limite: Int = null, desde: Int = null): [Pedido!]!
}

type RefreshPayload {
  accessToken: String!
  refreshToken: String!
}

input RenglonInput {
  productoId: Int!
  cantidad: Int!
}

enum RolEnum {
  ADMIN
  CLIENTE
}

type Usuario {
  id: Int!
  nombre: String!
  email: String!
  rol: RolEnum!
}

input UsuarioInput {
  nombre: String!
  email: String!
  password: String!
}
